import pandas as pd

df = pd.read_csv('dataset/train.csv')
df_test = pd.read_csv('dataset/test.csv')
street_types = df['Street'].unique()  # 获取Street的唯一值
Alley_types = df['Alley'].value_counts(dropna=False)  # 显示alley 有多少类以及数量  drop na包含缺失值
LotShape_types = df['LotShape'].value_counts(dropna=False)
LandContour_types = df['LandContour'].value_counts(dropna=False)
Utilities_types = df['Utilities'].value_counts(dropna=False)
LotConfig_types = df['LotConfig'].value_counts(dropna=False)
LandSlope_types = df['LandSlope'].value_counts(dropna=False)
Neighborhood_types = df['Neighborhood'].value_counts(dropna=False)
Condition1_types = df['Condition1'].value_counts(dropna=False)
Condition2_types = df['Condition2'].value_counts(dropna=False)
BldgType_types = df['BldgType'].value_counts(dropna=False)
HouseStyle_types = df['HouseStyle'].value_counts(dropna=False)
OverallQual_types = df['OverallQual'].value_counts(dropna=False)
OverallCond_types = df['OverallCond'].value_counts(dropna=False)
YearBuilt_types = df['YearBuilt'].value_counts(dropna=False)
YearRemodAdd_types = df['YearRemodAdd'].value_counts(dropna=False)
RoofStyle_types = df['RoofStyle'].value_counts(dropna=False)
RoofMatl_types = df['RoofMatl'].value_counts(dropna=False)
Exterior1st_types = df['Exterior1st'].value_counts(dropna=False)
Exterior2nd_types = df['Exterior2nd'].value_counts(dropna=False)
MasVnrType_types = df['MasVnrType'].value_counts(dropna=False)
MasVnrArea_types = df['MasVnrArea'].value_counts(dropna=False)
ExterQual_types = df['ExterQual'].value_counts(dropna=False)
ExterCond_types = df['ExterCond'].value_counts(dropna=False)
Foundation_types = df['Foundation'].value_counts(dropna=False)
BsmtQual_types = df['BsmtQual'].value_counts(dropna=False)
BsmtCond_types = df['BsmtCond'].value_counts(dropna=False)
BsmtExposure_types = df['BsmtExposure'].value_counts(dropna=False)
BsmtFinType1_types = df['BsmtFinType1'].value_counts(dropna=False)
BsmtFinType2_types = df['BsmtFinType2'].value_counts(dropna=False)
BsmtFinSF1_types = df['BsmtFinSF1'].value_counts(dropna=False)
BsmtFinSF2_types = df['BsmtFinSF2'].value_counts(dropna=False)
BsmtUnfSF_types = df['BsmtUnfSF'].value_counts(dropna=False)
TotalBsmtSF_types = df['TotalBsmtSF'].value_counts(dropna=False)
Heating_types = df['Heating'].value_counts(dropna=False)
HeatingQC_types = df['HeatingQC'].value_counts(dropna=False)
CentralAir_types = df['CentralAir'].value_counts(dropna=False)
Electrical_types = df['Electrical'].value_counts(dropna=False)
F1stFlrSF_types = df['1stFlrSF'].value_counts(dropna=False)
F2ndFlrSF_types = df['2ndFlrSF'].value_counts(dropna=False)
LowQualFinSF_types = df['LowQualFinSF'].value_counts(dropna=False)
GrLivArea_types = df['GrLivArea'].value_counts(dropna=False)
BsmtFullBath_types = df['BsmtFullBath'].value_counts(dropna=False)
BsmtHalfBath_types = df['BsmtHalfBath'].value_counts(dropna=False)
FullBath_types = df['FullBath'].value_counts(dropna=False)
HalfBath_types = df['FullBath'].value_counts(dropna=False)
BedroomAbvGr_types = df['BedroomAbvGr'].value_counts(dropna=False)
KitchenAbvGr_types = df['KitchenAbvGr'].value_counts(dropna=False)
KitchenQual_types = df['KitchenQual'].value_counts(dropna=False)
TotRmsAbvGrd_types = df['TotRmsAbvGrd'].value_counts(dropna=False)
Functional_types = df['Functional'].value_counts(dropna=False)
Fireplace_types = df['Fireplaces'].value_counts(dropna=False)
FireplaceQu_types = df['FireplaceQu'].value_counts(dropna=False)
GarageType_types = df['GarageType'].value_counts(dropna=False)
GarageYrBlt_types = df['GarageYrBlt'].value_counts(dropna=False)
GarageFinish_types = df['GarageFinish'].value_counts(dropna=False)
GarageCars_types = df['GarageCars'].value_counts(dropna=False)
GarageArea_types = df['GarageArea'].value_counts(dropna=False)
GarageQual_types = df['GarageQual'].value_counts(dropna=False)
GarageCond_types = df['GarageCond'].value_counts(dropna=False)
PavedDrive_types = df['PavedDrive'].value_counts(dropna=False)
WoodDeckSF_types = df['WoodDeckSF'].value_counts(dropna=False)
OpenPorchSF_types = df['OpenPorchSF'].value_counts(dropna=False)
EnclosedPorch_types = df['EnclosedPorch'].value_counts(dropna=False)
F3SsnPorch_types = df['3SsnPorch'].value_counts(dropna=False)
ScreenPorch_types = df['ScreenPorch'].value_counts(dropna=False)
PoolArea_types = df['PoolArea'].value_counts(dropna=False)
PoolQC_types = df['PoolQC'].value_counts(dropna=False)
Fence_types = df['Fence'].value_counts(dropna=False)
MiscFeature_types = df['MiscFeature'].value_counts(dropna=False)
MiscVal_types = df['MiscVal'].value_counts(dropna=False)
MoSold_types = df['MoSold'].value_counts(dropna=False)
YrSold_types = df['YrSold'].value_counts(dropna=False)
SaleType_types = df['SaleType'].value_counts(dropna=False)
SaleCondition_types = df['SaleCondition'].value_counts(dropna=False)


alley_saleprice = df[['LotShape', 'SalePrice']]

df['LotShape'] = df['LotShape'].replace({'IR1': 'IR', 'IR2': 'IR', 'IR3': 'IR'})
print(df.groupby('Alley')['SalePrice'].describe())
df_process = df[['Neighborhood','HouseStyle','OverallQual','YearBuilt','YearRemodAdd','Heating','CentralAir','1stFlrSF',
          '2ndFlrSF','GrLivArea','FullBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd','Fireplaces','GarageArea',
          'SaleCondition','SalePrice']]

# 保存为 Excel 文件
#df_process.to_csv('dataset/train_process.csv', index=False)  # index=False 表示不保存行索引
test_process = df_test[['Neighborhood','HouseStyle','OverallQual','YearBuilt','YearRemodAdd','Heating','CentralAir','1stFlrSF',
          '2ndFlrSF','GrLivArea','FullBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd','Fireplaces','GarageArea',
          'SaleCondition']]
test_process.to_csv('dataset/test_process.csv', index=False)